import { MigrationInterface, QueryRunner } from "typeorm";

export class Educenter1781687724945 implements MigrationInterface {
    name = 'Educenter1781687724945'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "otp_codes" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "otp_codes" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "teacher_attendance" DROP COLUMN "teacher_id"`);
        await queryRunner.query(`ALTER TABLE "teacher_attendance" ADD "teacher_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "teacher_salaries" DROP COLUMN "teacher_id"`);
        await queryRunner.query(`ALTER TABLE "teacher_salaries" ADD "teacher_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "group_students" DROP COLUMN "group_id"`);
        await queryRunner.query(`ALTER TABLE "group_students" ADD "group_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "group_students" DROP COLUMN "student_id"`);
        await queryRunner.query(`ALTER TABLE "group_students" ADD "student_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "assigned_to"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "assigned_to" uuid`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "created_by" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "holidays" DROP COLUMN "branch_id"`);
        await queryRunner.query(`ALTER TABLE "holidays" ADD "branch_id" uuid`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "schedules" DROP COLUMN "group_id"`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD "group_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP COLUMN "branch_id"`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD "branch_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quizzes" DROP COLUMN "group_id"`);
        await queryRunner.query(`ALTER TABLE "quizzes" ADD "group_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quiz_questions" DROP COLUMN "quiz_id"`);
        await queryRunner.query(`ALTER TABLE "quiz_questions" ADD "quiz_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quiz_options" DROP COLUMN "question_id"`);
        await queryRunner.query(`ALTER TABLE "quiz_options" ADD "question_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quiz_results" DROP COLUMN "quiz_id"`);
        await queryRunner.query(`ALTER TABLE "quiz_results" ADD "quiz_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quiz_results" DROP COLUMN "student_id"`);
        await queryRunner.query(`ALTER TABLE "quiz_results" ADD "student_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "student_id"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "student_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "group_id"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "group_id" uuid`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "received_by"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "received_by" uuid`);
        await queryRunner.query(`ALTER TABLE "parents" DROP CONSTRAINT "UQ_c94c3cea9b43a18c81269ded41d"`);
        await queryRunner.query(`ALTER TABLE "parents" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "parents" ADD "user_id" uuid`);
        await queryRunner.query(`ALTER TABLE "parents" ADD CONSTRAINT "UQ_c94c3cea9b43a18c81269ded41d" UNIQUE ("user_id")`);
        await queryRunner.query(`ALTER TABLE "student_parents" DROP COLUMN "student_id"`);
        await queryRunner.query(`ALTER TABLE "student_parents" ADD "student_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "student_parents" DROP COLUMN "parent_id"`);
        await queryRunner.query(`ALTER TABLE "student_parents" ADD "parent_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "user_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "materials" DROP COLUMN "group_id"`);
        await queryRunner.query(`ALTER TABLE "materials" ADD "group_id" uuid`);
        await queryRunner.query(`ALTER TABLE "materials" DROP COLUMN "teacher_id"`);
        await queryRunner.query(`ALTER TABLE "materials" ADD "teacher_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leads" DROP COLUMN "source_id"`);
        await queryRunner.query(`ALTER TABLE "leads" ADD "source_id" uuid`);
        await queryRunner.query(`ALTER TABLE "leads" DROP COLUMN "interest_subject_id"`);
        await queryRunner.query(`ALTER TABLE "leads" ADD "interest_subject_id" uuid`);
        await queryRunner.query(`ALTER TABLE "leads" DROP COLUMN "assigned_admin_id"`);
        await queryRunner.query(`ALTER TABLE "leads" ADD "assigned_admin_id" uuid`);
        await queryRunner.query(`ALTER TABLE "leads" DROP COLUMN "branch_id"`);
        await queryRunner.query(`ALTER TABLE "leads" ADD "branch_id" uuid`);
        await queryRunner.query(`ALTER TABLE "leads" DROP COLUMN "student_id"`);
        await queryRunner.query(`ALTER TABLE "leads" ADD "student_id" uuid`);
        await queryRunner.query(`ALTER TABLE "call_logs" DROP COLUMN "lead_id"`);
        await queryRunner.query(`ALTER TABLE "call_logs" ADD "lead_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "call_logs" DROP COLUMN "admin_id"`);
        await queryRunner.query(`ALTER TABLE "call_logs" ADD "admin_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP COLUMN "branch_id"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD "branch_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory_logs" DROP COLUMN "item_id"`);
        await queryRunner.query(`ALTER TABLE "inventory_logs" ADD "item_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory_logs" DROP COLUMN "action_by"`);
        await queryRunner.query(`ALTER TABLE "inventory_logs" ADD "action_by" uuid`);
        await queryRunner.query(`ALTER TABLE "book_sales" DROP COLUMN "student_id"`);
        await queryRunner.query(`ALTER TABLE "book_sales" ADD "student_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "book_sales" DROP COLUMN "item_id"`);
        await queryRunner.query(`ALTER TABLE "book_sales" ADD "item_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "book_sales" DROP COLUMN "sold_by"`);
        await queryRunner.query(`ALTER TABLE "book_sales" ADD "sold_by" uuid`);
        await queryRunner.query(`ALTER TABLE "homework_assignments" DROP COLUMN "group_id"`);
        await queryRunner.query(`ALTER TABLE "homework_assignments" ADD "group_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "homework_assignments" DROP COLUMN "teacher_id"`);
        await queryRunner.query(`ALTER TABLE "homework_assignments" ADD "teacher_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "homework_submissions" DROP COLUMN "homework_id"`);
        await queryRunner.query(`ALTER TABLE "homework_submissions" ADD "homework_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "homework_submissions" DROP COLUMN "student_id"`);
        await queryRunner.query(`ALTER TABLE "homework_submissions" ADD "student_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "subject_id"`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "subject_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "teacher_id"`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "teacher_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "grades" DROP COLUMN "student_id"`);
        await queryRunner.query(`ALTER TABLE "grades" ADD "student_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "grades" DROP COLUMN "teacher_id"`);
        await queryRunner.query(`ALTER TABLE "grades" ADD "teacher_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "grades" DROP COLUMN "group_id"`);
        await queryRunner.query(`ALTER TABLE "grades" ADD "group_id" uuid`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD "created_by" uuid`);
        await queryRunner.query(`ALTER TABLE "discounts" DROP COLUMN "student_id"`);
        await queryRunner.query(`ALTER TABLE "discounts" ADD "student_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "discounts" DROP COLUMN "group_id"`);
        await queryRunner.query(`ALTER TABLE "discounts" ADD "group_id" uuid`);
        await queryRunner.query(`ALTER TABLE "contracts" DROP COLUMN "student_id"`);
        await queryRunner.query(`ALTER TABLE "contracts" ADD "student_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "manager_id"`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "manager_id" uuid`);
        await queryRunner.query(`ALTER TABLE "attendances" DROP COLUMN "schedule_id"`);
        await queryRunner.query(`ALTER TABLE "attendances" ADD "schedule_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "attendances" DROP COLUMN "student_id"`);
        await queryRunner.query(`ALTER TABLE "attendances" ADD "student_id" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "attendances" DROP COLUMN "marked_by"`);
        await queryRunner.query(`ALTER TABLE "attendances" ADD "marked_by" uuid`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "attendances" DROP COLUMN "marked_by"`);
        await queryRunner.query(`ALTER TABLE "attendances" ADD "marked_by" character varying`);
        await queryRunner.query(`ALTER TABLE "attendances" DROP COLUMN "student_id"`);
        await queryRunner.query(`ALTER TABLE "attendances" ADD "student_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "attendances" DROP COLUMN "schedule_id"`);
        await queryRunner.query(`ALTER TABLE "attendances" ADD "schedule_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "branches" DROP COLUMN "manager_id"`);
        await queryRunner.query(`ALTER TABLE "branches" ADD "manager_id" character varying`);
        await queryRunner.query(`ALTER TABLE "contracts" DROP COLUMN "student_id"`);
        await queryRunner.query(`ALTER TABLE "contracts" ADD "student_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "discounts" DROP COLUMN "group_id"`);
        await queryRunner.query(`ALTER TABLE "discounts" ADD "group_id" character varying`);
        await queryRunner.query(`ALTER TABLE "discounts" DROP COLUMN "student_id"`);
        await queryRunner.query(`ALTER TABLE "discounts" ADD "student_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "expenses" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "expenses" ADD "created_by" character varying`);
        await queryRunner.query(`ALTER TABLE "grades" DROP COLUMN "group_id"`);
        await queryRunner.query(`ALTER TABLE "grades" ADD "group_id" character varying`);
        await queryRunner.query(`ALTER TABLE "grades" DROP COLUMN "teacher_id"`);
        await queryRunner.query(`ALTER TABLE "grades" ADD "teacher_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "grades" DROP COLUMN "student_id"`);
        await queryRunner.query(`ALTER TABLE "grades" ADD "student_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "teacher_id"`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "teacher_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "groups" DROP COLUMN "subject_id"`);
        await queryRunner.query(`ALTER TABLE "groups" ADD "subject_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "homework_submissions" DROP COLUMN "student_id"`);
        await queryRunner.query(`ALTER TABLE "homework_submissions" ADD "student_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "homework_submissions" DROP COLUMN "homework_id"`);
        await queryRunner.query(`ALTER TABLE "homework_submissions" ADD "homework_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "homework_assignments" DROP COLUMN "teacher_id"`);
        await queryRunner.query(`ALTER TABLE "homework_assignments" ADD "teacher_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "homework_assignments" DROP COLUMN "group_id"`);
        await queryRunner.query(`ALTER TABLE "homework_assignments" ADD "group_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "book_sales" DROP COLUMN "sold_by"`);
        await queryRunner.query(`ALTER TABLE "book_sales" ADD "sold_by" character varying`);
        await queryRunner.query(`ALTER TABLE "book_sales" DROP COLUMN "item_id"`);
        await queryRunner.query(`ALTER TABLE "book_sales" ADD "item_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "book_sales" DROP COLUMN "student_id"`);
        await queryRunner.query(`ALTER TABLE "book_sales" ADD "student_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory_logs" DROP COLUMN "action_by"`);
        await queryRunner.query(`ALTER TABLE "inventory_logs" ADD "action_by" character varying`);
        await queryRunner.query(`ALTER TABLE "inventory_logs" DROP COLUMN "item_id"`);
        await queryRunner.query(`ALTER TABLE "inventory_logs" ADD "item_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "inventory_items" DROP COLUMN "branch_id"`);
        await queryRunner.query(`ALTER TABLE "inventory_items" ADD "branch_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "call_logs" DROP COLUMN "admin_id"`);
        await queryRunner.query(`ALTER TABLE "call_logs" ADD "admin_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "call_logs" DROP COLUMN "lead_id"`);
        await queryRunner.query(`ALTER TABLE "call_logs" ADD "lead_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "leads" DROP COLUMN "student_id"`);
        await queryRunner.query(`ALTER TABLE "leads" ADD "student_id" character varying`);
        await queryRunner.query(`ALTER TABLE "leads" DROP COLUMN "branch_id"`);
        await queryRunner.query(`ALTER TABLE "leads" ADD "branch_id" character varying`);
        await queryRunner.query(`ALTER TABLE "leads" DROP COLUMN "assigned_admin_id"`);
        await queryRunner.query(`ALTER TABLE "leads" ADD "assigned_admin_id" character varying`);
        await queryRunner.query(`ALTER TABLE "leads" DROP COLUMN "interest_subject_id"`);
        await queryRunner.query(`ALTER TABLE "leads" ADD "interest_subject_id" character varying`);
        await queryRunner.query(`ALTER TABLE "leads" DROP COLUMN "source_id"`);
        await queryRunner.query(`ALTER TABLE "leads" ADD "source_id" character varying`);
        await queryRunner.query(`ALTER TABLE "materials" DROP COLUMN "teacher_id"`);
        await queryRunner.query(`ALTER TABLE "materials" ADD "teacher_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "materials" DROP COLUMN "group_id"`);
        await queryRunner.query(`ALTER TABLE "materials" ADD "group_id" character varying`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD "user_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "student_parents" DROP COLUMN "parent_id"`);
        await queryRunner.query(`ALTER TABLE "student_parents" ADD "parent_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "student_parents" DROP COLUMN "student_id"`);
        await queryRunner.query(`ALTER TABLE "student_parents" ADD "student_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "parents" DROP CONSTRAINT "UQ_c94c3cea9b43a18c81269ded41d"`);
        await queryRunner.query(`ALTER TABLE "parents" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "parents" ADD "user_id" character varying`);
        await queryRunner.query(`ALTER TABLE "parents" ADD CONSTRAINT "UQ_c94c3cea9b43a18c81269ded41d" UNIQUE ("user_id")`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "received_by"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "received_by" character varying`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "group_id"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "group_id" character varying`);
        await queryRunner.query(`ALTER TABLE "payments" DROP COLUMN "student_id"`);
        await queryRunner.query(`ALTER TABLE "payments" ADD "student_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quiz_results" DROP COLUMN "student_id"`);
        await queryRunner.query(`ALTER TABLE "quiz_results" ADD "student_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quiz_results" DROP COLUMN "quiz_id"`);
        await queryRunner.query(`ALTER TABLE "quiz_results" ADD "quiz_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quiz_options" DROP COLUMN "question_id"`);
        await queryRunner.query(`ALTER TABLE "quiz_options" ADD "question_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quiz_questions" DROP COLUMN "quiz_id"`);
        await queryRunner.query(`ALTER TABLE "quiz_questions" ADD "quiz_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "quizzes" DROP COLUMN "group_id"`);
        await queryRunner.query(`ALTER TABLE "quizzes" ADD "group_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "rooms" DROP COLUMN "branch_id"`);
        await queryRunner.query(`ALTER TABLE "rooms" ADD "branch_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "schedules" DROP COLUMN "group_id"`);
        await queryRunner.query(`ALTER TABLE "schedules" ADD "group_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD "user_id" character varying`);
        await queryRunner.query(`ALTER TABLE "holidays" DROP COLUMN "branch_id"`);
        await queryRunner.query(`ALTER TABLE "holidays" ADD "branch_id" character varying`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "created_by"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "created_by" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP COLUMN "assigned_to"`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD "assigned_to" character varying`);
        await queryRunner.query(`ALTER TABLE "group_students" DROP COLUMN "student_id"`);
        await queryRunner.query(`ALTER TABLE "group_students" ADD "student_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "group_students" DROP COLUMN "group_id"`);
        await queryRunner.query(`ALTER TABLE "group_students" ADD "group_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "teacher_salaries" DROP COLUMN "teacher_id"`);
        await queryRunner.query(`ALTER TABLE "teacher_salaries" ADD "teacher_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "teacher_attendance" DROP COLUMN "teacher_id"`);
        await queryRunner.query(`ALTER TABLE "teacher_attendance" ADD "teacher_id" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "otp_codes" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "otp_codes" ADD "user_id" character varying`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP COLUMN "user_id"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD "user_id" character varying NOT NULL`);
    }

}
